### ISSUE TITLE
Investigate why MySQL connections from PHP running under Apache do not work in combination with fuse mode

### ISSUE THREAD

**Issue by vadimberezniker** [GoogleCloudPlatform/cloudsql-proxy#7] opened 2016-03-16 21:06 UTC
Strangely enough the same code works when running the PHP script directly.

The proxy sees a request for the socket, but the MySQL PHP driver does not appear to follow the symlink in this case.

**Comment by kurtisvg** [comment] 2018-07-16 16:25
Closing - this issue hasn't been updated for over 6 months and appears to be abandoned.

**Comment by Carrotman42** [comment] 2018-07-17 14:04
I mean, the issue is potentially still a problem. Why close it? Imo closed issues are harder to find, especially when not all closed issues are actually fixed or otherwise done with.

**Comment by kurtisvg** [comment] 2018-07-17 16:57
Apologies if I closed it incorrectly - when I skimmed over the linked issue it seemed like the issue had been resolved by instructing the user to use the `-instances` flag.

**Comment by enocom** [comment] 2021-02-08 22:46
Seeing as how as this is almost five years old and there aren't any steps to reproduction this, I'm going to close it.

If this is still a problem, feel free to re-open and provide steps to reproduce.

**Closed by enocom** 2021-02-08 22:46 UTC
Labels: priority: p3, type: bug
