### ISSUE TITLE
Unable to connect with Private IP - proxy uses port 3307

### ISSUE THREAD

**Issue by y0ssar1an** [GoogleCloudPlatform/cloudsql-proxy#370] opened 2020-04-06 03:06 UTC
I have a Postgres 12 instance with a private IP that I'm trying to connect to.

```
> docker run -v ~/path/to/my-service-account-key.json:/config -p '127.0.0.1:5432:5432' --rm gcr.io/cloudsql-docker/gce-proxy /cloud_sql_proxy -instances=my-project:us-central1:main-primary=tcp:0.0.0.0:5432 -credential_file=/config
2020/04/06 02:55:02 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
2020/04/06 02:55:02 using credential file for authentication; email=my-service-account@my-project.iam.gserviceaccount.com
2020/04/06 02:55:03 Listening on 0.0.0.0:5432 for my-project:us-central1:main-primary
2020/04/06 02:55:03 Ready for new connections
2020/04/06 02:55:07 New connection for "my-project:us-central1:main-primary"
2020/04/06 02:56:23 couldn't connect to "my-project:us-central1:main-primary": dial tcp 172.25.240.2:3307: connect: connection refused
```
```
> psql postgresql://postgres@localhost:5432/postgres
psql: error: could not connect to server: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
Why is it trying to connect on port 3307? That's a MySQL port.

**Comment by Carrotman42** [comment] 2020-04-06 14:16
3306 the port for MySQL.

3307 is the custom port used the the Cloud SQL Proxy protocol. This part is
working as intended.

Where are you running the proxy? For private IP setups, you have to be
running on the same private network.

**Comment by dmahugh** [comment] 2020-04-06 16:56
FYI, the use of 3307 is standard for proxy connections as described in the [troubleshooting section](https://cloud.google.com/sql/docs/mysql/sql-proxy#troubleshooting) of the docs.

Regarding Private IP, you need to have access to the VPC. See [Requirements for Private IP](https://cloud.google.com/sql/docs/mysql/private-ip#requirements_for_private_ip).

**Comment by dmahugh** [comment] 2020-04-06 16:59
Closing this now, but if the above guidance doesn't resolve your issue let us know.

**Closed by dmahugh** 2020-04-06 16:59 UTC
Labels: type: question

**Comment by y0ssar1an** [comment] 2020-04-06 20:51
>Where are you running the proxy? For private IP setups, you have to be
running on the same private network.
I was running it on my laptop, trying to connect to a db with a private IP. I guess this is not possible.
Thank you for replying so quickly!
