### ISSUE TITLE
Certificates broken in Go 1.11

### ISSUE THREAD

**Issue by forrestdix** [GoogleCloudPlatform/cloudsql-proxy#202] opened 2018-08-28 19:00 UTC
Go 1.11 made changes to certificate verification in crypto/x509. In particular, it added a check to verify that the common name is a valid host name. "my-project:us-central1:my-instance" fails this check. As a result, the following error is returned.

x509: Common Name is not a valid hostname: my-project:my-instance

**Comment by kurtisvg** [comment] 2018-08-28 19:03
This appears to be a duplicate of #194, and was fixed in #196.

**Closed by kurtisvg** 2018-08-28 19:03 UTC
Labels: duplicate

**Comment by b3ntly** [comment] 2018-08-28 21:10
This bit us in production. Our fault for not pinning go versions, I guess we got lax with Go's stellar history of backwards compatibility. The quick solution is to pin your golang versions to before this change (we just did 1.10) and re-build/deploy. 

Can we get test cases against this happening in the future? Or is this a community driven project.

**Comment by hfwang** [comment] 2018-08-30 22:15
I'm not sure how we could actually have put together a test case against this. I don't think there is a way to define what go versions a codebase must be pinned to.

Mind you, we found out about this earlier since we run close to Go's head and not the latest release version, and thus patched it.
