### ISSUE TITLE
error new ephemeral certificate expires too soon

### ISSUE THREAD

**Issue by Rossco8** [GoogleCloudPlatform/cloudsql-proxy#647] opened 2021-03-03 04:47 UTC
## Bug Description

- Attempting to connect to Postgres13 DB from Google Cloud Shell
- Database was created with
```
gcloud beta sql instances create l42db \
        --no-assign-ip \
        --network=projects/${PROJECT_ID}/global/networks/$PRIVATE_NETWORK_NAME \
        --availability-type=zonal \
        --no-backup \
        --database-version=POSTGRES_13 \
        --insights-config-query-insights-enabled \
        --maintenance-release-channel=production \
        --require-ssl \
        --storage-auto-increase \
        --storage-size=10 \
        --storage-type=HDD \
        --zone=$ZONE_A \
        --cpu=1 \
        --memory=3840MiB \
        --root-password=$RAND_PW \
        --disk-encryption-key=projects/${PROJECT_ID}/locations/$GPC_REGION/keyRings/$KMS_RING/cryptoKeys/$PG_DISK_KEY_ID \
        --maintenance-window-day=SUN \
        --maintenance-window-hour=00 \
        --quiet
```

Error
```
couldn't connect to "l42-dev21:australia-southeast1:l42db": new ephemeral certificate expires too soon: current time: 2021-03-03 04:23:59.882497779 +0000 UTC m=+77.280749396,
```

## From tab-1

```
$ ./cloud_sql_proxy -instances=l42-dev21:australia-southeast1:l42db=tcp:5432
```

## From tab-2

```
$ psql "host=127.0.0.1 port=5432 sslmode=disable dbname=l42db user=postgres"
```

## Error Output
```
2021/03/03 04:22:42 Rlimits for file descriptors set to {Current = 8500, Max = 1048576}
2021/03/03 04:22:45 Listening on 127.0.0.1:5432 for l42-dev21:australia-southeast1:l42db
2021/03/03 04:22:45 Ready for new connections
2021/03/03 04:23:58 New connection for "l42-dev21:australia-southeast1:l42db"
2021/03/03 04:23:59 ephemeral certificate ({Certificate:[[48 130 3 134 48 130 2 110 160 3 2 1 2 2 4 100 81 234 117 48 13 6 9 42 134 72 134 247 13 1 1 11 5 0 48 129 141 49 45 48 43 6 3 85 4 46 19 36 101 50 53 56 50 98 100 55 45 102 99 100 53 45 52 50 97 97 45 56 49 99 55 45 56 98 101 53
 50 98 55 100 48 52 97 48 49 57 48 55 6 3 85 4 3 19 48 71 111 111 103 108 101 32 67 108 111 117 100 32 83 81 76 32 83 105 103 110 105 110 103 32 67 65 32 108 97 107 101 52 50 45 100 101 118 50 49 58 108 97 107 52 50 100 98 49 20 48 18 6 3 85 4 10 19 11 71 111 111 103 108 101 44 32 73 1
10 99 49 11 48 9 6 3 85 4 6 19 2 85 83 48 30 23 13 50 49 48 51 48 51 48 52 50 50 53 57 90 23 13 50 49 48 51 48 51 48 53 50 51 53 57 90 48 59 49 22 48 20 6 3 85 4 3 19 13 99 108 111 117 100 115 113 108 45 117 115 101 114 49 20 48 18 6 3 85 4 10 19 11 71 111 111 103 108 101 44 32 73 1109
9 49 11 48 9 6 3 85 4 6 19 2 85 83 48 130 1 34 48 13 6 9 42 134 72 134 247 13 1 1 1 5 0 3 130 1 15 0 48 130 1 10 2 130 1 1 0 221 20 25 199 170 235 117 37 231 245 172 114 153 189 253 188 23 164 49 161 199 224 105 151 89 118 103 197 196 15 199 105 135 100 116 164 167 155 159 215 151 232 
226 241 72 222 11 92 171 126 167 71 177 42 208 216 38 18 162 217 179 140 153 137 83 189 172 105 174 250 111 124 68 192 34 151 79 0 47 249 29 170 148 187 122 47 102 74 81 239 77 186 180 169 190 114 53 19 12 22 182 43 155 192 251 130 144 171 74 194 161 124 8 221 63 28 171 246 84 36 67 13
 229 38 189 11 130 32 229 247 9 227 170 37 184 196 220 5 85 12 212 173 207 160 130 223 178 151 113 223 29 191 115 3 138 49 129 13 55 140 79 100 63 35 111 178 156 39 103 173 177 10 223 172 204 55 244 239 84 122 211 24 109 77 2 84 62 152 91 139 180 40 14 6 217 110 107 38 249 149 255 176 
67 55 206 84 145 73 133 18 127 18 212 23 46 64 198 70 103 123 102 32 187 97 154 220 105 197 126 121 153 154 226 230 7 64 44 41 120 28 212 19 159 123 10 195 173 148 7 171 197 150 153 5 51 145 2 3 1 0 1 163 63 48 61 48 9 6 3 85 29 19 4 2 48 0 48 48 6 3 85 29 17 4 41 48 39 129 22 114 111 
115 115 99 111 101 46 112 105 99 111 64 103 109 97 105 108 46 99 111 109 160 13 6 1 85 160 8 3 6 0 13 0 0 0 0 48 13 6 9 42 134 72 134 247 13 1 1 11 5 0 3 130 1 1 0 108 175 234 56 201 178 34 96 113 133 30 23 62 64 56 23 6 89 23 182 173 115 32 161 211 70 5 238 244 149 197 14 152 162 237 
107 110 75 37 8 121 58 198 209 24 179 74 19 139 250 33 246 70 106 34 246 42 91 163 230 74 85 223 145 104 111 247 96 112 133 13 97 93 120 30 202 177 116 95 204 142 14 222 60 229 26 18 190 120 8 211 143 231 152 229 68 204 144 187 197 177 44 124 126 159 54 80 225 203 70 208 145 148 43 236
 47 82 60 240 236 10 163 202 46 12 240 164 147 233 122 153 8 226 124 62 219 44 234 56 106 3 54 113 30 65 146 110 56 228 72 189 35 219 166 75 184 75 178 95 238 72 141 229 108 32 190 152 6 36 37 166 201 56 129 52 28 63 34 40 16 218 201 248 124 203 86 136 152 121 73 77 78 176 74 60 183 15
5 187 209 102 222 252 173 72 46 35 160 226 76 240 90 154 222 93 34 85 22 200 76 99 89 248 96 52 26 150 222 215 135 177 112 36 141 79 116 39 17 246 189 112 252 115 96 170 38 200 198 120 13 83 30 120 70 131 80 127]] PrivateKey:0xc00037ff80 SupportedSignatureAlgorithms:[] OCSPStaple:[] Si
gnedCertificateTimestamps:[] Leaf:0xc0004ce000}) error: new ephemeral certificate expires too soon: current time: 2021-03-03 04:23:59.882497779 +0000 UTC m=+77.280749396, certificate expires: 2021-03-03 04:26:26 +0000 UTC
2021/03/03 04:23:59 couldn't connect to "l42-dev21:australia-southeast1:l42db": new ephemeral certificate expires too soon: current time: 2021-03-03 04:23:59.882497779 +0000 UTC m=+77.280749396, certificate expires: 2021-03-03 04:26:26 +0000 UTC
2021/03/03 04:24:30 New connection for "l42-dev21:australia-southeast1:l42db"
2021/03/03 04:24:30 Throttling refreshCfg(l42-dev21:australia-southeast1:l42db): it was only called 31.046037115s ago
```

**Comment by enocom** [comment] 2021-03-03 15:40
Just to confirm, what version of gcloud are you using?

**Comment by enocom** [comment] 2021-03-03 16:38
Likely the same issue as #643.

**Comment by kurtisvg** [comment] 2021-03-03 17:48
In addition, confirming the version of the proxy being used would help.

**Comment by Rossco8** [comment] 2021-03-03 19:36
```
rossoc@cloudshell:~ (rdev1cloudsql-307904)$ gcloud --version
Google Cloud SDK 329.0.0
alpha 2021.02.19
app-engine-go 1.9.71
app-engine-java 1.9.86
app-engine-python 1.9.91
app-engine-python-extras 1.9.91
beta 2021.02.19
bigtable
bq 2.0.65
cbt 0.9.0
cloud-build-local 0.5.2
cloud-datastore-emulator 2.1.0
core 2021.02.19
datalab 20190610
gsutil 4.59
kind 0.7.0
kpt 0.37.1
minikube 1.17.1
pubsub-emulator 0.4.0
skaffold 1.20.0
rosscoo@cloudshell:~ (rdev1cloudsql-307904)$
```

cloud proxy was from
```
wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
```

**Comment by enocom** [comment] 2021-03-03 20:03
Thanks @Rossco8. I think you're running v1.20.0, but would you mind telling me what you get from this command?

```
./cloud_sql_proxy --version
```

**Comment by Rossco8** [comment] 2021-03-03 20:17
Yes, it was downloaded just yesterday

```
Cloud SQL Proxy: 1.20.0+linux.amd64
```

**Comment by enocom** [comment] 2021-03-03 20:21
OK. In that case, this is a duplicate of #643, for which I'm working on a fix right now.

The draft PR is here: https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/648. Hoping to land it ASAP as soon as I confirm it does in fact resolve the issue. We'll track progress on #643 in the mean time.

**Closed by enocom** 2021-03-03 20:21 UTC
Labels: needs more info, priority: p1, type: bug

**Comment by Rossco8** [comment] 2021-03-03 20:22
Great, thanks @enocom
