### ISSUE TITLE
Local development for Cloud Run with Docker Compose - error with v1.17

### ISSUE THREAD

**Issue by maelga** [GoogleCloudPlatform/cloudsql-proxy#430] opened 2020-08-18 12:19 UTC
## Description
I am running the exact same docker compose configuration explained in this tutorial with v1.16 and it works fine:
https://cloud.google.com/community/tutorials/cloud-run-local-dev-docker-compose

Updating **docker-compose.sql.yml** to the v1.17 image throws this error `invalid json file "/root/keys/keyfile.json": open /root/keys/keyfile.json: permission denied` and stops the container.

```
version: '3'  
services:
    app:
        ...
        sql_proxy:
            image: gcr.io/cloudsql-docker/gce-proxy:1.16   <----- changing to 1.17 breaks
        ...
```

This is the command I run to have my local environment connect to Cloud SQL database:
```
docker-compose \
-f docker-compose.yml \                 <---- custom file with my own app
-f docker-compose.access.yml \          <---- file as per tutorial
-f docker-compose.sql.yml \             <---- file as per tutorial
up
```

## Container log
With v1.16

```
020/08/18 11:25:08 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
2020/08/18 11:25:08 using credential file for authentication; email=[my-service-account]@[my-project].iam.gserviceaccount.com
2020/08/18 11:25:09 Listening on /cloudsql/[my-project]:us-west1:[my-db-instance] for [my-project]:us-west1:[my-db-instance]
2020/08/18 11:25:09 Ready for new connections
```

With v1.17

```
2020/08/18 11:26:20 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
2020/08/18 11:26:20 invalid json file "/root/keys/keyfile.json": open /root/keys/keyfile.json: permission denied
```

I am not sure whether this should be reported as an issue with version 1.17 of Cloud SQL proxy or whether the documentation needs to be updated.

**Comment by kurtisvg** [comment] 2020-08-18 15:29
Hi @maelga,

This is because in 1.17 of the image uses a `non-root` by default, since this provides better security. This user doesn't have access to the file you've mounted in the container. I think your options should be:

1. Edit permissions on the file so it can access it `sudo chown 65532 /path/to/file` (`65532` is the uid of the non-root user)
2. Run the container as a user that already has access (looks like docker-compose has a `user` key)

**Comment by HalfdanJ** [comment] 2020-10-08 01:13
I have a similar issue, running the image while mounting `~/.config:/root/.config` to the docker image in 1.16 automatically uses the application-default credentials. But in 1.17 it fails with `google: could not find default credentials. `. Let me know if this is a separate issue you want me to file a bug for.

**Comment by kurtisvg** [comment] 2020-10-12 22:23
@HalfdanJ The problem is that the container doesn't run as `root` by default - you likely need to mount it into `/nonroot/.config` instead (or override the default user as a mentioned above). 

I'm going to close this issue - I've reported the issue to the original author, but it's a community tutorial and we don't have any power to edit.

**Closed by kurtisvg** 2020-10-12 22:23 UTC
Labels: type: docs

**Comment by ToddKopriva** [comment] 2020-11-04 00:49
The fact that this is a Community tutorial doesn't keep us from editing and fixing this. I'm re-opening this issue.
