### ISSUE TITLE
Brief summary of what bug or error was observed

### ISSUE THREAD

**Issue by pwaterz** [GoogleCloudPlatform/cloudsql-proxy#660] opened 2021-03-05 19:48 UTC
## Bug Description

The current latest build image  is causing a deployments to fail: gcr.io/cloudsql-docker/gce-proxy@sha256:ccf18b0c2ee4a65b55c424cc7eec9881999bf61e7ed5368a62e88f84e2c7a87f

Error:
```
Get "[hidden]": exec: "gcloud": executable file not found in $PATH
```

## Example code (or command)
Kubernets manifest
```
        - name: cloud-sql-proxy
          # It is recommended to use the latest version of the Cloud SQL proxy
          # Make sure to update on a regular schedule!
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          resources:
            requests:
              cpu: "20m"
          command:
            - "/cloud_sql_proxy"

            # If connecting from a VPC-native GKE cluster, you can use the
            # following flag to have the proxy connect over private IP
            # - "-ip_address_types=PRIVATE"

            # Replace DB_PORT with the port the proxy should listen on
            # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
            - "[hidden]"
          securityContext:
            # The default Cloud SQL proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true```

## Environment

1. OS type and version: gke
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): gcr.io/cloudsql-docker/gce-proxy@sha256:ccf18b0c2ee4a65b55c424cc7eec9881999bf61e7ed5368a62e88f84e2c7a87f

**Comment by enocom** [comment] 2021-03-05 19:58
Thanks for the bug report @pwaterz. This is a duplicate of https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/655. We're currently testing the dev release and will cut a new patch version as soon as we're convinced it's solid (likely this afternoon). Follow https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/643 for updates.

In the meantime, we recommend pinning to v1.19.0.

**Closed by enocom** 2021-03-05 19:58 UTC
Labels: type: bug

**Comment by pwaterz** [comment] 2021-03-05 20:02
Ahh my bad, thanks!
