### ISSUE TITLE
Unable to connect to Postgres in GKE using Go Library

### ISSUE THREAD

**Issue by buckhx** [GoogleCloudPlatform/cloudsql-proxy#210] opened 2018-09-22 17:35 UTC
I've created an app that is the same as the [hook_test postgres dialer](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/proxy/dialers/postgres/hook_test.go) example and am able to run in locally, but when packaged as a deployment and pushed into a GKE cluster receive an error when connecting. Using alpine3.8 as the base image the following error message is return: 

```
 "failed to parse addr: "localhost:5432". It should conform to the regular expression "^\\[(.+)\\]:[0-9]+$"
```

Example docker file
```
FROM golang:1.11 as builder
WORKDIR /workspace
COPY . . 
go build -o app

FROM alpine:3.8 as runner
RUN apk --no-cache add ca-certificates 
COPY --from=builder /workspace/app ./app
```
Example DSN:
```
'host=project:zone:instance user=postgres dbname=mydb password=mypass sslmode=disable'
```

**Comment by kurtisvg** [comment] 2018-09-23 03:02
When you say the example is running locally, did you run it in the container locally as well?

Can you provide a more complete snippet of your code where the connection is being made?

**Comment by Megalepozy** [comment] 2018-11-02 10:43
I had an error like that few days ago, for me it was that the host parameter value used at sql.Open was indeed localhost... surprise surprise :) maybe its the same 4 u, also, check that the driver is cloudsqlpostgres.

My issue is that after passing that issue I get :
2018/11/02 10:30:24 Error when trying to get driver:
 "Post https://www.googleapis.com/sql/v1beta4/projects/[project-name]/instances/[db-instance]/createEphemeral?alt=json&prettyPrint=false: x509: certificate signed by unknown authority"

I saw at a past issue that it was said that I need to include the certificate on my own and that the way to do it is appearing at the Dockerfile, the problem is that there is no Dockerfile at this repo today... so if anyone know how to do that pls let me know :)

**Comment by Megalepozy** [comment] 2018-11-07 09:32
@buckhx I'm not sure if it will solve ur issue but at ur Dockerfile update golang to version 1.10 as 1.11 created a bug with cloud sql proxy (u can learn more at https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/203 and other issues as well)

**Comment by kurtisvg** [comment] 2018-11-15 18:49
There hasn't been a response from OP for over 30 days, so we are closing this. If anyone else notices the issues please feel free to reopen.

**Closed by kurtisvg** 2018-11-15 18:49 UTC
Labels: Type: Question
