### ISSUE TITLE
Logs are being treated as errors in stackdriver

### ISSUE THREAD

**Issue by HarithJ** [GoogleCloudPlatform/cloudsql-proxy#223] opened 2018-11-15 08:03 UTC
I am running my application in GKE and have deployed cloudsql-proxy as a side-container in the pod. Here is how I have defined the container configurations for it:
```containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.13
          command: ["sh", "-c",
            "/cloud_sql_proxy -instances={{ PRODUCTION_DB_INSTANCE_CONNECTION_NAME }}=tcp:5432 -credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
```

However, the cloudsql-proxy container logs on stackdriver are being displayed as ERRORS, where as they should just be displayed as `info`.

**Comment by kurtisvg** [comment] 2018-11-15 18:41
Closing as is a duplicate of #149.

Hi @HarithJ,

In PR #150 the `log_debug_stdout` flag was added. Setting this flag to true will log messages to stdout.

**Closed by kurtisvg** 2018-11-15 18:41 UTC
