### ISSUE TITLE
cloud proxy having lag spikes on random moments

### ISSUE THREAD

**Issue by bcoghe** [GoogleCloudPlatform/cloudsql-proxy#131] opened 2017-11-20 09:17 UTC
Dear,

I am experiencing lag spikes on my GKE cluster that runs a flask restplus api. I think the problem is in the cloud sql proxy that calls the database. It seems to happen on random moments and is indendent on the amount of traffic. It's the first time I am using this combination so i'm not sure if it is really cloud sql but i found similar issues online. Checking the logs gives these kinds of errors for a 20 second lag spike:

2017/11/19 05:08:28 New connection for "df002dds:europe-west1:signal-database"  

2017/11/19 05:08:28 Client closed local connection on 127.0.0.1:3306  

2017/11/19 05:08:28 New connection for "df002dds:europe-west1:signal-database"  

2017/11/19 05:08:28 Client closed local connection on 127.0.0.1:3306  

2017/11/19 05:08:48 New connection for "df002dds:europe-west1:signal-database"  

2017/11/19 05:08:48 Client closed local connection on 127.0.0.1:3306

Any ideas?

In attachment some more logs. The kubernetes commands also seem to be related to these lag spikes.

<img width="960" alt="gcp issue" src="https://user-images.githubusercontent.com/15378385/33010757-f55d9f2a-cddb-11e7-927a-c6250f77e1fb.png">

**Comment by kszarlej** [comment] 2017-12-04 10:45
@bcoghe that might be related to https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/94

**Comment by AthenaShi** [comment] 2017-12-21 01:37
This might be caused by #94, have to say sorry that I'm just aware of this problem.  I've created an internal ticket and it will be prioritized.

**Comment by hfwang** [comment] 2018-03-30 03:09
Closing since this looks to be a dupe.

**Closed by hfwang** 2018-03-30 03:09 UTC
