### ISSUE TITLE
Access denied when connecting to firebase functions 

### ISSUE THREAD

**Issue by irohitb** [GoogleCloudPlatform/cloudsql-proxy#312] opened 2019-09-27 12:52 UTC
**Note:** Copying and pasting it from [firebase functions issue I just made](https://github.com/firebase/firebase-functions/issues/564)

### [REQUIRED] Version info

**node:** 10

**firebase-functions:** 7.2.4

**firebase-tools:** 7.2.4

**firebase-admin:** 8.5.0

### [REQUIRED] Test case

In my SQL (index.js) file, I am doing something like this. The instructions here are very indentical to what is mention in [offical docs of using cloud functions with cloud SQL](https://cloud.google.com/functions/docs/sql)

```
const connectionName = config.DB_CONNECTION_NAME
console.log(`Connection name: ${config.DB_CONNECTION_NAME}`)
const configSQL = {
	host: config.DB_HOST,
	user: config.DB_USER,
	password: config.DB_PASSWORD,
	database: config.DB_DATABASE,
}

// Connection to cloud sql in production

if (!process.env.dev) {
	configSQL.socketPath = `/cloudsql/${connectionName}`
}

//SQL Config
const pool = mysql.createPool(configSQL)

// Checking if it was connected sucessfully or not on server startup
pool.getConnection((err, connection) => {
	if (err) {
		console.error('error connecting: ' + err)
		return
	}
	console.log('connected as id ' + connection.threadId)
	connection.release()
	return
})
```

And then in my main Index.js file, I am importing it and creating an endpoint like this
```
const functions = require('firebase-functions')
const admin = require('firebase-admin')
admin.initializeApp()
const glob = require("glob");
const camelCase = require("camelcase");
const mysql = require('./src/database/sql/index') // eslint-disable-line no-unused-vars
const files = glob.sync('./**/*.f.js', { cwd: __dirname, ignore: './node_modules/**'});
for(let f=0,fl=files.length; f<fl; f++){
  const file = files[f];
  const functionName = camelCase(file.slice(0, -5).split('/').join('_')); // Strip off '.f.js'
  if (!process.env.FUNCTION_NAME || process.env.FUNCTION_NAME === functionName) {
    exports[functionName] = require(file);
  }
}
```

On deploying it when I got to logs of firebase functions, it shows me the following error in my functions log 

<img width="1132" alt="Screenshot 2019-09-27 at 6 08 30 PM" src="https://user-images.githubusercontent.com/32276134/65769709-ddb8ff00-e151-11e9-8010-ff5d8812511e.png">

<img width="1355" alt="Screenshot 2019-09-27 at 6 17 19 PM" src="https://user-images.githubusercontent.com/32276134/65770260-58cee500-e153-11e9-9d97-69d4831c247d.png">

**Note: 1** I am pretty sure that my username and password are correct 
**Note: 2** I have only created the user and database in my cloud SQL settings and haven't done anything else (like setting up SSL, or whitelisting anything)
**Note: 3** Project backend, Readme.md in the repo contains some info about initializing (just in case)
**Note: 4** Yes, I am setting up my environment variables

### [REQUIRED] Steps to reproduce

```firebase deploy --only functions```

Check the function logs, This function above should log error on an error and successful thread on the connection 

```
pool.getConnection((err, connection) => {
	if (err) {
		console.error('error connecting: ' + err)
		return
	}
	console.log('connected as id ' + connection.threadId)
	connection.release()
	return
})
```

### [REQUIRED] Expected behavior

it should successfully connect to firebase 

### [REQUIRED] Actual behavior
 It should have Deployed functions 

### Were you able to successfully deploy your functions?
Yes

**Comment by kurtisvg** [comment] 2019-09-27 15:53
Closing, as issues on this repo are only for problems with the Cloud SQL proxy. 

However, the fact that you are getting that "Authentication denied" error means the issue is at the MySQL authentication layer. You are either using the incorrect password for that db user, or that db user doesn't have the correct permissions to connect in that way.

**Closed by kurtisvg** 2019-09-27 15:53 UTC
Labels: type: question

**Comment by Carrotman42** [comment] 2019-09-27 16:26
To augment Kurtis's suggested root causes, check that the hostname of your created user is appropriate as per these docs: https://cloud.google.com/sql/docs/mysql/sql-proxy#user

**Comment by irohitb** [comment] 2019-09-27 22:25
@kurtisvg, @Carrotman42 : Can you just go through it for once and let me know if you can see something wrong by having a quick Glimpse

@Carrotman42 I went through these docs: https://cloud.google.com/functions/docs/sql 
The cloudSQl docs (the link you shared me), the functions-sql docs (the above link( have no mention about setting it up by doing that much hasle

I know it's too much to ask but can you please help me in fixing it?  These are the environment values I am passing to the Cloud SQL Config 

<img width="1183" alt="Screenshot 2019-09-28 at 3 44 16 AM" src="https://user-images.githubusercontent.com/32276134/65805332-a9b9fa00-e1a2-11e9-8e6d-b2f1548486ba.png">

(Please refer to the code snippet above)

Where my cloudSQL looks like this 

<img width="466" alt="Screenshot 2019-09-28 at 3 42 22 AM" src="https://user-images.githubusercontent.com/32276134/65805346-b5a5bc00-e1a2-11e9-9be2-16bd3c94aa89.png">
<img width="479" alt="Screenshot 2019-09-28 at 3 42 50 AM" src="https://user-images.githubusercontent.com/32276134/65805347-b5a5bc00-e1a2-11e9-85ae-e88293c12896.png">
<img width="488" alt="Screenshot 2019-09-28 at 3 43 02 AM" src="https://user-images.githubusercontent.com/32276134/65805348-b5a5bc00-e1a2-11e9-9390-fc5158c588d0.png">


How I am invoking functions/ calling them, the code for it is above.

**Comment by kurtisvg** [comment] 2019-09-30 16:13
MySQL account settings look correct to me. I would verify that your password is correct, and that it's correctly reaching your application (probably by logging it when the app starts up)?

**Comment by irohitb** [comment] 2019-10-04 17:54
@kurtisvg  I am 100% sure password is correct and tried logging in on deployment just before SQL initialisation. 
Again, I am able to make request using workbench but not when I deploy my functions.  

@Carrotman42

**Comment by kurtisvg** [comment] 2019-10-04 18:22
A [quick google search](https://stackoverflow.com/questions/20353402/access-denied-for-user-testlocalhost-using-password-yes-except-root-user) shows that this error could can also be caused by insufficient privileges for the user to access the database.

If privileges isn't the correct solution, I suggest asking on StackOverflow, where more experiences folks might be able to help. I'd suggest making sure to include as many relevant details as possible, including source code.

**Comment by irohitb** [comment] 2019-10-04 19:38
@kurtisvg  I will try to figure out but just in case there are two active bounties I am running but haven't got any response. 

https://stackoverflow.com/questions/58117314/er-access-denied-error-cloudsql
https://stackoverflow.com/questions/38478451/gae-cloudsql-error-access-denied-for-user-rootcloudsqlproxy

Thanks for your help though :)
