### ISSUE TITLE
Allow for dynamic credentials file

### ISSUE THREAD

**Issue by SudoSpartanDan** [GoogleCloudPlatform/cloudsql-proxy#770] opened 2021-05-01 14:53 UTC
Currently, the proxy can establish a connection using static credentials, but there doesn't seem to be a clean way to re-establish a connection if the credentials file changes. This can be problematic, especially in a Kubernetes sidecar serving the proxy to other pods.

Possibly a flag to check the credentials periodically and restart if needed?

Example:

```
.\cloud_sql_proxy.exe -instances=myproject-12345:us-central1:test=tcp:5433 -watch-credentials
```

**Comment by SudoSpartanDan** [comment] 2021-05-01 15:03
This is what I'm doing for the sidecar at the moment to get this working via an inline bash script.

```yaml
# Cloud SQL Auth Proxy Side Car
- name: {{ .Values.cloudSql.containerName }}
  image: {{ .Values.cloudSql.image }}:{{ .Values.cloudSql.tag }}
  command:  ["/bin/sh", "-c"]
  args:
    - |-
        echo $(date "+%Y/%m/%d %H:%M:%S") 'Starting proxy';
        LTIME=`stat -c %Z /etc/secrets/service_account.json`;
        /cloud_sql_proxy \
          -instances={{ .Values.cloudSql.project }}:{{ .Values.cloudSql.region }}:{{ .Values.cloudSql.instance }}=tcp:{{ .Values.cloudSql.port }} \
          -credential_file=/etc/secrets/service_account.json & PPID=$!;
        echo $(date "+%Y/%m/%d %H:%M:%S") 'Proxy started';
        while true;
        do ATIME=`stat -c %Z /etc/secrets/service_account.json`;
        if [ "$ATIME" != "$LTIME" ];
        then echo $(date "+%Y/%m/%d %H:%M:%S") 'Credentials changed, restarting proxy';
        kill -s SIGTERM "$PPID";
        /cloud_sql_proxy \
          -instances={{ .Values.cloudSql.project }}:{{ .Values.cloudSql.region }}:{{ .Values.cloudSql.instance }}=tcp:{{ .Values.cloudSql.port }} \
          -credential_file=/etc/secrets/service_account.json & PPID=$!;
        echo $(date "+%Y/%m/%d %H:%M:%S") 'Proxy restarted, process pid:' $PPID;
        echo $PPID;
        LTIME=$ATIME;
        fi;
        sleep 15;
        if ! kill -0 $PPID 2>/dev/null;
        then echo $(date "+%Y/%m/%d %H:%M:%S") 'Proxy not alive, exiting';
        exit 1; 
        fi;
        done;
  securityContext:
    {{- toYaml .Values.securityContext | nindent 12 }}
  volumeMounts:
  - name: secrets
    mountPath: /etc/secrets
    readOnly: true
```

**Comment by enocom** [comment] 2021-05-01 20:57
>  in a Kubernetes sidecar serving the proxy to other pods

Would you mind elaborating what you mean here?

**Comment by SudoSpartanDan** [comment] 2021-05-02 02:25
I have a sidecar container initializing the proxy so other containers can use that proxy to establish connections to the database. That sidecar is using a shared mount volume with the secrets file. Another sidecar container loads that file with the SA Info and then updates the credentials when the lease on the secret has expired.

The issue I run into is when the credentials file is updated, the proxy doesn't re-establish a connection with the new credentials, and when the proxy is used, we get the following error:

```bash
2021/04/30 23:10:54 failed to refresh the ephemeral certificate for database-name:db-region:db-instance before expir
ing: Post https://sqladmin.googleapis.com/sql/v1beta4/projects/database-name/instances/db-instance/createEphemeral?alt
=json&prettyPrint=false: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Invalid JWT Signature."}
```

The proxy container doesn't fail on this though and the container just keeps running.

**Comment by enocom** [comment] 2021-05-02 02:37
OK. Thanks for the clarification.

**Comment by enocom** [comment] 2021-05-03 15:05
Closing this as a duplicate of #205. Let's continue the discussion as needed over there.

**Closed by enocom** 2021-05-03 15:05 UTC
Labels: priority: p2, type: feature request
