### ISSUE TITLE
Feature Request: Better support for proxy as daemon

### ISSUE THREAD

**Issue by dhduvall** [GoogleCloudPlatform/cloudsql-proxy#290] opened 2019-06-21 21:45 UTC
This is related to #4, but I don't think it's possible to run `cloud-sql-proxy` as a service other services can depend on because  it doesn't do its own daemonization. Using the `daemon` utility would still allow the service to be online (as far as `systemd` is concerned, so it'll start dependent services) before `cloud-sql-proxy` is actually listening on its socket, because the external utility can't know when that point occurs.

I know that `systemd` isn't universal, but `github.com/coreos/go-systemd/daemon.SdNotify()` doesn't do anything if `$NOTIFY_SOCKET` isn't set, and the package produces only a 16k archive (x86_64 Linux), so it's a small weight to carry around for a one-time operation even on systems where it's not relevant.

**Comment by pperez** [comment] 2020-09-21 18:32
Ah, exactly what i was looking for ... seems like i'm going to add a little sleep in my script :/

**Comment by enocom** [comment] 2021-02-09 23:28
Duplicate of #234.

**Closed by enocom** 2021-02-09 23:28 UTC
Labels: type: feature request

**Comment by dhduvall** [comment] 2021-02-10 01:24
I'd say that #234 is not strictly a duplicate of this one, since this issue is specifically about making sure that `systemd` doesn't mark the proxy service as online until the proxy is ready to take requests, and #234 introduces the requirement that the proxy be self-daemonizing.

Without diving too deeply into the possible implementation, I admit that it may be possible to daemonize in such a way that the grandparent process doesn't exit until the grandchild tells it that its ready to handle requests, but the communication between them needed to do so isn't nearly as simple as the naive implementation (such as using the `daemon()` library call), where the grandparent exits as soon as the `fork()` is successful (and thus telling _its_ parent that the daemon is ready).

**Comment by enocom** [comment] 2021-02-10 18:19
Thanks for the note @dhduvall. 

For now, I'm going to add your note about making sure the proxy works well with `systemd` in #234 and consider that issue over there to be a tracking issue generally for this work.
