### ISSUE TITLE
CloudSQL Proxy gets 404 on trying to connect to instance when built with go get

### ISSUE THREAD

**Issue by rick-pri** [GoogleCloudPlatform/cloudsql-proxy#353] opened 2020-02-17 09:20 UTC
As per https://github.com/googleapis/google-api-go-client/issues/427 there is an issue with building the proxy from master with `go get` because it uses `v0.15.0` of the `google-api-go-client` but there is an issue with using this api after `v0.13.0`.  Also see #331 and #346 (which actually references the actual 404 that is returned).

I tried changing the `go.mod` to `v0.13.0` but after issuing a `go build` in the `cmd/cloud_sql_proxy` directory it checked out `v0.14.0` and had modified the go.mod file to that version too.  So at this point I'm guessing some other dependency has a requirement on `v0.14.0`.

**Comment by kurtisvg** [comment] 2020-02-17 21:28
Ok, I was actually able to reproduce this by starting in a docker container as opposed to my local copy for some reason:
```sh
$ docker run --rm -it golang:1
$ go get github.com/GoogleCloudPlatform/cloudsql-proxy/cmd/cloud_sql_proxy
```
I confirmed it cloned at 231cffdfe5a16e0f922416ceb095f2c28783ad2d, then built the proxy (`go build` from `/go/src/github.com/GoogleCloudPlatform/cloudsql-proxy/cmd/cloud_sql_proxy`)  and saw the following:
```sh
$ go: extracting google.golang.org/api v0.15.0
```

Then running the proxy (`/go/bin/cloud_sql_proxy -instances=project:region:instance=tcp:3306`):
```
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/sql/v1beta4/sql/v1beta4/projects/project/instances/instance?alt=json&amp;prettyPrint=false</code> was not found on this server.  <ins>That’s all we know.</ins>
```

Not quite sure why it works locally - I'm going to reopen and dedup against #331.

**Comment by kurtisvg** [comment] 2020-02-17 21:29
Duplicate of #331

**Closed by kurtisvg** 2020-02-17 21:29 UTC
Labels: duplicate
