### ISSUE TITLE
Very slow performance when using the proxy

### ISSUE THREAD

**Issue by omerlh** [GoogleCloudPlatform/cloudsql-proxy#516] opened 2020-10-29 10:49 UTC
## Bug Description

I am running load test before trying it in production, and I noticed a very huge performance overhead when using the proxy. 

## How to reproduce

  1.  Create cloud sql proxy with the following config:
![image](https://user-images.githubusercontent.com/6730584/97558362-ae279680-19e4-11eb-9d47-18dac56b5184.png)
  2. Create a test VM - `e2-standard-16 (16 vCPUs, 64 GB memory)`
 3. Run cloud sql proxy as a process (using the latest version binary).

Results:
```
pgbench -c 500 -j 2 -t 10000 postgres -h <> // directly using the public ip
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "C.UTF-8"
  are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
starting vacuum...end.
transaction type: <builtin: TPC-B (sort of)>
scaling factor: 50
query mode: simple
number of clients: 500
number of threads: 2
number of transactions per client: 10000
number of transactions actually processed: 5000000/5000000
latency average = 227.917 ms
tps = 2193.783436 (including connections establishing)
tps = 2193.795428 (excluding connections establishing)

$ pgbench -c 500 -j 2 -t 10000 postgres. // with the proxy
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "C.UTF-8"
  are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
starting vacuum...end.
transaction type: <builtin: TPC-B (sort of)>
scaling factor: 50
query mode: simple
number of clients: 500
number of threads: 2
number of transactions per client: 10000
number of transactions actually processed: 5000000/5000000
latency average = 343.441 ms
tps = 1455.854525 (including connections establishing)
tps = 1455.863860 (excluding connections establishing)
```

Is this expected? Maybe something I mis-configured?

## Environment

1. OS type and version: Ubuntu
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): Cloud SQL Proxy: 1.18.0

**Comment by shubha-rajan** [comment] 2020-10-29 19:39
Hi @omerlh, thanks for opening the issue! We're working on reproducing it and will follow up soon.

**Comment by shubha-rajan** [comment] 2020-11-04 01:29
To follow up, we were able to replicate the numbers you were seeing when using the same settings for pgbench as you had used above. 
Command: `pgbench -c 500 -j 2 -t 10000 postgres -h [instance public IP] -U postgrespgbench -c 500 -j 2 -t 10000 postgres -h [instance public IP] -U postgres`
```
transaction type: <builtin: TPC-B (sort of)>
scaling factor: 50
query mode: simple
number of clients: 500
number of threads: 2
number of transactions per client: 10000
number of transactions actually processed: 5000000/5000000
latency average = 212.110 ms
tps = 2357.271871 (including connections establishing)
tps = 2357.282742 (excluding connections establishing)
```
Command: `pgbench -c 500 -j 2 -t 10000 postgres -h 127.0.0.1 -U postgres`
```
transaction type: <builtin: TPC-B (sort of)>
scaling factor: 50
query mode: simple
number of clients: 500
number of threads: 2
number of transactions per client: 10000
number of transactions actually processed: 5000000/5000000
latency average = 339.099 ms
tps = 1474.496186 (including connections establishing)
tps = 1474.504326 (excluding connections establishing)
```
After that, we tested a few variables that could have caused the overhead . 
1. First, we tried running pgbench using SSL, and comparing it to both the proxy connection and the direct public IP connection. The SSL connection took slightly longer (around 218ms, compared to the 212ms for public IP without SSL), but that difference was negligible compared to the large overhead we were seeing for the proxy.

Command: 
```
pgbench -c 500 -j 2 -t 10000 "sslmode=verify-ca \
sslrootcert=server-ca.pem \
sslcert=client-cert.pem sslkey=client-key.pem \
hostaddr=[Public IP Address] \
user=postgres dbname=postgres"
```
```
transaction type: <builtin: TPC-B (sort of)>
scaling factor: 50
query mode: simple
number of clients: 500
number of threads: 2
number of transactions per client: 10000
number of transactions actually processed: 5000000/5000000
latency average = 218.770 ms
tps = 2285.503365 (including connections establishing)
tps = 2285.516762 (excluding connections establishing)
```
2. We then tried running the proxy using both TCP and Unix sockets, but the difference in average latencies for both of those proxy modes was negligible (~344ms vs ~339ms)
Command: `pgbench -c 500 -j 2 -t 10000 postgres -h ~/cloudsql/[instance connection name] -U postgres  `
```
transaction type: <builtin: TPC-B (sort of)>
scaling factor: 50
query mode: simple
number of clients: 500
number of threads: 2
number of transactions per client: 10000
number of transactions actually processed: 5000000/5000000
latency average = 344.194 ms
tps = 1452.669338 (including connections establishing)
tps = 1452.676626 (excluding connections establishing)
```
3. We ran the benchmarks again with 25, 50, and 100 clients instead of 500 and found that at 50 connections, the overhead latency is much, much smaller (~10ms instead of ~100ms). The numbers we were seeing were around ~16ms for SSL without the proxy and 28 ms for SSL with the proxy. At 25ms, we got a latency of ~9ms without the proxy and 13ms with the proxy. This makes sense given that the proxy would have more overheard per connection, given that there are actually 4x the number of connections involved (sending/receiving w/client-side proxy, and sending/receiving with server-side proxy) . At this point the Cloud SQL instance was at 100%, which shows the size of the instance is the bottle neck. It also makes sense that more connections would cause disproportional overhead given PG's connection pooling model (1 process per connection).

When it comes to optimizing, we compared the [myCopy](c16eb2a5f10575dce3cadca843ae3b36/proxy/proxy/common.go#L58) function in the proxy’s source code with the [io.Copy](https://golang.org/src/io/io.go?s=12980:13040#L398) function in the stdLib, and noticed the only real difference was the buffer size. We tried adjusting the default buffer size, but didn't see any noticeable performance improvements. We aren't sure what else we can do to reduce overhead (but are open to suggestions).

**Comment by omerlh** [comment] 2020-11-04 06:39
First, thank you for taking the time and diving into the issue. Really appreciated!
I also pointed GCP support to this issue, and they pointed me to #87 and #88 - which seems to suggest that measuring the actual application might be more important, as connection pooling could help here. 
This is the results when testing our app using ab, 1000 requests, 100 concurent:
![image](https://user-images.githubusercontent.com/6730584/98077366-ca11b900-1e78-11eb-88a9-26bdb6a4bf7b.png)

The table shows the difference between direct connection and connection via the proxy, and look like the mean and median are pretty similar (the numbers are milliseconds).

So this got me really confused TBH, as it might suggest we could ignore the slower performance reporter by pgbench.

**Comment by shubha-rajan** [comment] 2021-02-10 00:06
Closing this issue, because the large overhead for connections only happens at very high connection volumes and shouldn't be an issue in typical use cases.

**Closed by shubha-rajan** 2021-02-10 00:06 UTC
Labels: priority: p3, type: bug
