### ISSUE TITLE
Document change in base image starting with 1.16

### ISSUE THREAD

**Issue by macrozone** [GoogleCloudPlatform/cloudsql-proxy#1014] opened 2021-11-12 14:52 UTC
## Question

We ran cloudql-proxy for over a year without any problem. We use it as sidecars in kubernetes.

We never updated it, but i decided to bring it up to date (also to be prepared to version 2). So i updated it to 1.27.0.

it now no longer starts, the sidecar containers keeps crashing, but unfortunatly, it does not log anything.

## Additional Context

the command that is triggered is  the following (taken from the helm chart):

```
 /cloud_sql_proxy -instances={{ .Values.cloudsql.projectId}}:{{ .Values.cloudsql.region}}:{{ default .Release.Namespace .Values.cloudsql.instanceId }}=tcp:5432 -credential_file=/secrets/cloudsql/credentials.json &
  ```

any idea what is going wrong?

**Comment by macrozone** [comment] 2021-11-12 16:13
Ok, I found the problem.

We used `/bin/sh` to start it, described here: https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/262#issuecomment-690805913

**Comment by enocom** [comment] 2021-11-12 19:02
Glad you found the problem @macrozone. What kind of documentation would have helped here?

**Comment by macrozone** [comment] 2021-11-14 16:06
> Glad you found the problem @macrozone. What kind of documentation would have helped here?

well i checked the releases and given the minor number bump, it should not contain any breaking change. The problem lies on the provided docker images which should not have changed significally. I think the docs where the different versions of the images are referred should mention the pros and cons for each version and it should be more clear, that the alpine is probably the one to take when coming from older versions, not the "recommended" one

**Comment by enocom** [comment] 2021-11-15 04:32
Duplicate of https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/317.

**Comment by enocom** [comment] 2021-11-18 05:25
Thinking some more about this, we can add a note to the README alerting users of versions prior to 1.16 about a change in the base image from alpine to distroless.

**Closed** 2022-03-01 19:29 UTC
Labels: priority: p2, type: docs, type: cleanup
