### ISSUE TITLE
connection reset by peer

### ISSUE THREAD

**Issue by hazcod** [GoogleCloudPlatform/cloudsql-proxy#779] opened 2021-05-06 13:21 UTC
## Bug Description

Hi! I have a private GKE AutoPilot cluster in which I run my cloudSQL proxy with following arguments to connect my my public+private Cloud SQL instance using Workload Identity.

Container arguments:
```
        - '/cloud_sql_proxy'
        - '-enable_iam_login'
        - '-ip_address_types=PRIVATE'
        - '-instances=foo=tcp:3127'
```

## Logs
```
2021/05/06 13:16:52 couldn't connect to "xxx": read tcp 10.82.0.226:46762->10.152.0.12:3307: read: connection reset by peer
2021/05/06 13:16:52 couldn't connect to "xxx": read tcp 10.82.0.226:46774->10.152.0.12:3307: read: connection reset by peer
2021/05/06 13:16:52 couldn't connect to "xxx": read tcp 10.82.0.226:46798->10.152.0.12:3307: read: connection reset by peer
2021/05/06 13:16:53 couldn't connect to "xxx": dial tcp 10.152.0.12:3307: connect: connection refused
2021/05/06 13:16:53 couldn't connect to "xxxx": dial tcp 10.152.0.12:3307: connect: connection refused
```

**Comment by hazcod** [comment] 2021-05-06 13:22
And since there are no healthchecks defined, I the CloudSQL sidecar container just dies silently until I restart it.

**Comment by kurtisvg** [comment] 2021-05-06 15:06
Can you provide any more information? What version are you running? Does restarting the proxy fix the issue? Are you able to reproduce the issue with any reliability? Is `10.152.0.12` your instance's IP? 

It's generally best to define your own healthcheck on your application that confirms connectivity issues, to help test the complete path. K8s has options to specify a [liveness HTTP request](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request).

**Comment by enocom** [comment] 2021-05-11 21:06
@hazcod Did you resolve the issue? Otherwise, would you mind reporting some more information about your environment?

**Comment by hazcod** [comment] 2021-05-12 09:16
I'm running the CloudSQL proxy on a Docker for Mac Kubernetes cluster.
Honestly I'm not sure what the cause is, but 10.82 is the subnet of the local k8s Pods.
Would be nice if the sidecar would die if connection dials fail.

**Comment by hazcod** [comment] 2021-05-12 12:59
Not sure what exactly triggers this, but still getting:
```
"could not initialize db foo: read: connection reset by peer"
```

**Comment by enocom** [comment] 2021-05-12 14:47
Does your deployment have access to the private instance? The proxy won't create a network path into a VPC. It requires such a path already exist.

**Comment by hazcod** [comment] 2021-05-18 12:28
Hmm, I'm seeing this in a GKE private cluster as wel where google services are enabled.
```
2021/05/18 12:25:50 Reading data from intigriti-hybrid-308608:europe-west1:hybrid-request-db had error: read tcp 10.82.0.75:57306->10.152.0.19:3307: read: connection reset by peer
2021/05/18 12:25:50 Reading data from intigriti-hybrid-308608:europe-west1:hybrid-request-db had error: read tcp 10.82.0.75:57304->10.152.0.19:3307: read: connection reset by peer
2021/05/18 12:25:50 couldn't connect to "intigriti-hybrid-308608:europe-west1:hybrid-request-db": read tcp 10.82.0.75:58678->10.152.0.19:3307: read: connection reset by peer
2021/05/18 12:25:50 couldn't connect to "intigriti-hybrid-308608:europe-west1:hybrid-request-db": read tcp 10.82.0.75:58674->10.152.0.19:3307: read: connection reset by peer
2021/05/18 12:25:50 couldn't connect to "intigriti-hybrid-308608:europe-west1:hybrid-request-db": read tcp 10.82.0.75:58670->10.152.0.19:3307: read: connection reset by peer
2021/05/18 12:25:52 New connection for "intigriti-hybrid-308608:europe-west1:hybrid-request-db"
2021/05/18 12:25:52 couldn't connect to "intigriti-hybrid-308608:europe-west1:hybrid-request-db": dial tcp 10.152.0.19:3307: connect: connection refused
2021/05/18 12:25:55 New connection for "intigriti-hybrid-308608:europe-west1:hybrid-request-db"
```

**Comment by enocom** [comment] 2021-05-18 19:10
It seems like we're talking about a handful of things here. I'm guessing this is a networking issue, but let's start by confirming that you can connect to your private IP Cloud SQL instance without involving GKE.

Can you run the proxy manually from within the VPC that has access to the Cloud SQL instance and connect successfully? Also, as @kurtisvg asked above, is 10.152.0.12 your instance's IP?

**Comment by hazcod** [comment] 2021-05-19 14:37
Oddly enough those subnets are supposedly for Australia 🤔 
https://cloud.google.com/vpc/docs/vpc

australia-southeast1 | 10.152.0.0/20 | 10.152.0.1 | 10.152.0.2 to 10.152.15.253

**Comment by hazcod** [comment] 2021-05-19 21:46
> Earlier you said:
> 
> > I cannot reproduce it reliably at this point.
> 
> How often do you see these errors? Can you connect successfully at all? Does restarting the proxy help?

The problem seems to go away after a cloudsql-proxy restart. It's happening after a while. (e.g. after 20 occasional queries)

**Comment by enocom** [comment] 2021-05-19 21:52
When you observe these errors, how many open connections does your database instance have? Also, what size database (CPU and memory) are you using?

I'm wondering if this is just the database limiting the number of additional connections.

**Comment by hazcod** [comment] 2021-05-20 05:23
I have 2x db-g1-small (postgres 13, HA) with `max_connections` db flag set to `100`.
But note that when the max connections is reached, postgresql will react with an error message instead of the machine denying the port request.

**Comment by enocom** [comment] 2021-05-20 14:57
Thanks @hazcod. 

So to summarize, you're seeing connection refused errors for your private IP Postgres instance using v1.22.0.

There are two distinct errors, one where dialing the instance fails (I assume 35.187.94.xxx is your database instance IP), and one where the proxy seems to be dialing an IP address (i.e., 10.152.0.12) totally unrelated to your database. Is that correct?

The problem goes away after a restart, but then appears again after a number of queries. Please confirm if you're consistently getting either one or both errors.

```
2021/05/06 13:16:53 couldn't connect to "xxx": dial tcp 10.152.0.12:3307: connect: connection refused
```
```
2021/05/12 12:58:09 couldn't connect to "foo": dial tcp 35.187.94.xxx:3307: connect: connection refused
```

Would you mind providing a minimal set of steps to reproduce? For instance, if you just connect from a VM to your private instance and run a handful of queries, does the same problem manifest? I'd like to try to reduce the scope here (GKE + vpc + private IP database leaves a lot of room for possible problems).

Thank you for your patience as we debug this.

**Comment by hazcod** [comment] 2021-05-21 07:27
@enocom To summarise:

1. Dialing the public CloudSQL instance IP via cloudsql-proxy will often fail during regular queries. (`35.187.94.xxx`)

2. 10.152.xxx.xxx is a range automatically assigned by the Private VPC Services connector defined here:
```tf
resource "google_compute_subnetwork" "gke_cluster_subnet" {
  project       = var.project_id
  name          = "${var.k8s_cluster_name}-subnet"
  region        = var.region
  network       = google_compute_network.k8svpc.name
  ip_cidr_range = "10.10.0.0/16"
  private_ip_google_access = true

  log_config {
    aggregation_interval = "INTERVAL_10_MIN"
    flow_sampling        = 0.5
    metadata             = "INCLUDE_ALL_METADATA"
  }
}

resource "google_compute_global_address" "k8s_vpc_private_ips" {
  project = var.project_id

  name          = "private-k8s-vpc-ips"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 16
  network       = google_compute_network.k8svpc.id
}

resource "google_service_networking_connection" "private_vpc_connection" {
  network                 = google_compute_network.k8svpc.id
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.k8s_vpc_private_ips.name]
}
```

It does reappear after X amount of queries. I'm not sure how I can provide a reliable PoC.

**Comment by hazcod** [comment] 2021-05-21 07:57
Now that I come to think of it, `private_ip_google_access = true` doesn't make sense when I define a `google_service_networking_connection`, so I'll have double VPC peering. Let me test this one out.

**Comment by hazcod** [comment] 2021-05-21 11:40
Seems the problem persists after only having 1 peering connection to google services (and redeploying GKE pods).

This is my local log where I only have things running, nothing more except healthchecks:
```
2021/05/21 11:13:22 Instance project:europe-west1:my-db2 closed connection
2021/05/21 11:13:22 Instance project:europe-west1:my-db2 closed connection
2021/05/21 11:13:26 New connection for "project:europe-west1:my-db2"
2021/05/21 11:13:28 Client closed local connection on 127.0.0.1:3126
2021/05/21 11:13:29 New connection for "project:europe-west1:my-db2"
2021/05/21 11:13:29 New connection for "project:europe-west1:my-db"
2021/05/21 11:14:35 Instance project:europe-west1:my-db closed connection
2021/05/21 11:14:35 Instance project:europe-west1:my-db closed connection
2021/05/21 11:14:38 New connection for "project:europe-west1:my-db"
2021/05/21 11:14:39 couldn't connect to "project:europe-west1:my-db": dial tcp 35.189.220.xxx:3307: connect: connection refused
2021/05/21 11:14:41 New connection for "project:europe-west1:my-db"
2021/05/21 11:14:41 Client closed local connection on 127.0.0.1:3127
2021/05/21 11:14:41 Client closed local connection on 127.0.0.1:3127
2021/05/21 11:14:41 Client closed local connection on 127.0.0.1:3126
2021/05/21 11:14:43 New connection for "project:europe-west1:my-db"
2021/05/21 11:14:43 New connection for "project:europe-west1:my-db"
2021/05/21 11:14:43 New connection for "project:europe-west1:my-db2"
2021/05/21 11:14:43 New connection for "project:europe-west1:my-db2"
2021/05/21 11:19:35 Instance project:europe-west1:my-db2 closed connection
2021/05/21 11:19:35 Instance project:europe-west1:my-db2 closed connection
2021/05/21 11:19:38 New connection for "project:europe-west1:my-db2"
2021/05/21 11:19:39 couldn't connect to "project:europe-west1:my-db2": dial tcp 35.187.94.xxx:3307: connect: connection refused
2021/05/21 11:19:41 New connection for "project:europe-west1:my-db2"
2021/05/21 11:19:41 Client closed local connection on 127.0.0.1:3126
2021/05/21 11:19:41 Client closed local connection on 127.0.0.1:3126
2021/05/21 11:19:41 Client closed local connection on 127.0.0.1:3127
2021/05/21 11:19:43 New connection for "project:europe-west1:my-db"
2021/05/21 11:19:43 New connection for "project:europe-west1:my-db"
2021/05/21 11:19:43 New connection for "project:europe-west1:my-db2"
2021/05/21 11:19:43 New connection for "project:europe-west1:my-db2"
2021/05/21 11:24:20 New connection for "project:europe-west1:my-db2"
2021/05/21 11:24:20 Instance project:europe-west1:my-db2 closed connection
2021/05/21 11:24:35 Instance project:europe-west1:my-db closed connection
2021/05/21 11:24:35 Instance project:europe-west1:my-db closed connection
2021/05/21 11:24:38 New connection for "project:europe-west1:my-db"
2021/05/21 11:24:39 couldn't connect to "project:europe-west1:my-db": dial tcp 35.189.220.xxx:3307: connect: connection refused
2021/05/21 11:24:41 New connection for "project:europe-west1:my-db"
2021/05/21 11:24:41 Client closed local connection on 127.0.0.1:3127
2021/05/21 11:24:41 Client closed local connection on 127.0.0.1:3127
2021/05/21 11:24:41 Client closed local connection on 127.0.0.1:3126
2021/05/21 11:24:43 New connection for "project:europe-west1:my-db"
2021/05/21 11:24:43 New connection for "project:europe-west1:my-db"
2021/05/21 11:24:43 New connection for "project:europe-west1:my-db2"
2021/05/21 11:24:43 New connection for "project:europe-west1:my-db2"
2021/05/21 11:28:22 Instance project:europe-west1:my-db2 closed connection
2021/05/21 11:28:23 Instance project:europe-west1:my-db2 closed connection
2021/05/21 11:28:26 New connection for "project:europe-west1:my-db2"
2021/05/21 11:28:29 New connection for "project:europe-west1:my-db2"
2021/05/21 11:29:43 Client closed local connection on 127.0.0.1:3126
2021/05/21 11:29:44 New connection for "project:europe-west1:my-db"
2021/05/21 11:33:20 Instance project:europe-west1:my-db closed connection
2021/05/21 11:33:20 Instance project:europe-west1:my-db closed connection
2021/05/21 11:33:23 New connection for "project:europe-west1:my-db"
2021/05/21 11:33:24 couldn't connect to "project:europe-west1:my-db": dial tcp 35.189.220.xxx:3307: connect: connection refused
2021/05/21 11:33:26 New connection for "project:europe-west1:my-db"
2021/05/21 11:33:26 Client closed local connection on 127.0.0.1:3127
2021/05/21 11:33:26 Client closed local connection on 127.0.0.1:3127
2021/05/21 11:33:26 Client closed local connection on 127.0.0.1:3126
2021/05/21 11:33:29 New connection for "project:europe-west1:my-db"
2021/05/21 11:33:29 New connection for "project:europe-west1:my-db"
2021/05/21 11:33:29 New connection for "project:europe-west1:my-db2"
2021/05/21 11:33:29 New connection for "project:europe-west1:my-db2"
2021/05/21 11:34:35 Instance project:europe-west1:my-db2 closed connection
2021/05/21 11:34:35 Instance project:europe-west1:my-db2 closed connection
2021/05/21 11:34:38 New connection for "project:europe-west1:my-db2"
2021/05/21 11:34:39 couldn't connect to "project:europe-west1:my-db2": dial tcp 35.187.94.xxx:3307: connect: connection refused
2021/05/21 11:34:41 New connection for "project:europe-west1:my-db2"
2021/05/21 11:34:41 Client closed local connection on 127.0.0.1:3126
2021/05/21 11:34:41 Client closed local connection on 127.0.0.1:3126
2021/05/21 11:34:41 Client closed local connection on 127.0.0.1:3127
2021/05/21 11:35:21 ephemeral certificate for instance project:europe-west1:my-db will expire soon, refreshing now.
2021/05/21 11:35:21 refreshing ephemeral certificate for instance project:europe-west1:my-db
2021/05/21 11:35:21 ephemeral certificate for instance project:europe-west1:my-db2 will expire soon, refreshing now.
2021/05/21 11:35:21 Scheduling refresh of ephemeral certifcate in 59m3.696601292s
2021/05/21 11:35:21 refreshing ephemeral certificate for instance project:europe-west1:my-db2
2021/05/21 11:35:21 Scheduling refresh of ephemeral certifcate in 59m3.793987166s
```

Notice the frequent `connect: connection refused` for both DBs.

**Comment by enocom** [comment] 2021-06-01 16:23
@hazcod Without steps to reproduce, it's hard to diagnose this problem. I'd recommend starting as simple as possible to debug the issue (simple app + proxy + private IP) to see if the same problem crops up. Until then, I'm going to close this.

**Comment by hazcod** [comment] 2022-02-23 17:21
Interestingly it's still occuring for me now with v1.28.1.
Some db calls will fail, cpu/mem/conns on cloudsql look fine.

```
2022/02/21 14:59:57 couldn't connect to "project:europe-west1:db": dial tcp 10.84.0.2:3307: connect: connection refused
```

**Comment by enocom** [comment] 2022-02-23 17:33
Have you ever been able to successfully connect to `10.84.0.2:3307` with the proxy as you've currently deployed it?

**Comment by hazcod** [comment] 2022-02-24 08:33
@enocom it works, except for the intermittent issues I describe here.

**Comment by enocom** [comment] 2022-02-24 16:41
What container runtime are you using?

**Comment by enocom** [comment] 2022-02-24 19:38
This is almost certainly a network problem, but I'd like to try to narrow down the problem a bit. `10.84.0.2:3307` is the IP address of your Cloud SQL instance's server-side proxy. If you're seeing intermittent failures to connect, that means an intermediate component is interfering with the connection.

A couple of thoughts:

- Do you have any firewall rules in place that might be blocking traffic to 3307?
- Can you reproduce this failure on a bare VM in the same VPC?

**Comment by hazcod** [comment] 2022-03-01 08:03
For ref, my firewall rules:

![image](https://user-images.githubusercontent.com/5222512/156128978-ce73d22b-9291-4113-84d2-3bc00ee4f3f1.png)


VPC creation terraform:
```hcl
# VPC
resource "google_compute_network" "k8svpc" {
  project                 = var.project_id
  name                    = "${var.k8s_cluster_name}-vpc"
  auto_create_subnetworks = false
  #delete_default_routes_on_create = true
}

# Subnet
resource "google_compute_subnetwork" "gke_cluster_subnet" {
  project       = var.project_id
  name          = "${var.k8s_cluster_name}-subnet"
  region        = var.region
  network       = google_compute_network.k8svpc.name
  ip_cidr_range = "10.10.0.0/16"
  private_ip_google_access = false

  log_config {
    aggregation_interval = "INTERVAL_10_MIN"
    flow_sampling        = 0.5
    metadata             = "INCLUDE_ALL_METADATA"
  }
}

resource "google_compute_global_address" "k8s_vpc_private_ips" {
  project = var.project_id

  name          = "private-k8s-vpc-ips"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 16
  network       = google_compute_network.k8svpc.id
}

resource "google_service_networking_connection" "private_vpc_connection" {
  network                 = google_compute_network.k8svpc.id
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.k8s_vpc_private_ips.name]
}

resource "google_compute_route" "egress_internet" {
  project          = var.project_id
  name             = "route-egress-internet"
  dest_range       = "0.0.0.0/0"
  network          = google_compute_network.k8svpc.name
  next_hop_gateway = "default-internet-gateway"
}

resource "google_compute_router" "k8svpc_router" {
  project = var.project_id
  name    = "k8svpc-router"
  region  = google_compute_subnetwork.gke_cluster_subnet.region
  network = google_compute_network.k8svpc.name
}

resource "google_compute_router_nat" "nat_router" {
  project = var.project_id

  name                               = "${google_compute_subnetwork.gke_cluster_subnet.name}-nat-router"
  router                             = google_compute_router.k8svpc_router.name
  region                             = google_compute_router.k8svpc_router.region
  nat_ip_allocate_option             = "MANUAL_ONLY"

  nat_ips = [
    google_compute_address.nat_egress_address.id,
  ]

  # only the gke nodes should be able to NAT to egress
  source_subnetwork_ip_ranges_to_nat = "LIST_OF_SUBNETWORKS"

  subnetwork {
    name                    = google_compute_subnetwork.gke_cluster_subnet.name
    source_ip_ranges_to_nat = ["ALL_IP_RANGES"]
  }

  log_config {
    enable = true
    filter = "ERRORS_ONLY"
  }
}

/*
resource "google_compute_firewall" "k8svpc_firewall_ingress_proxy" {
  name = "k8s-vpc-firewall-ingress-proxy"
  network = google_compute_network.k8svpc.self_link
  project = var.project_id

  description = "this only allows traffic for the proxy on the proxy listener IP."
  direction = "INGRESS"
  destination_ranges = ["${google_compute_address.ingress_lb_address.address}/32"]

  allow {
    protocol = "tcp"
    ports    = ["9300"]
  }
}

resource "google_compute_firewall" "k8svpc_firewall_egress_deny_ingress" {
  name = "k8s-vpc-firewall-egress-deny-ingress"
  network = google_compute_network.k8svpc.self_link
  project = var.project_id

  description = "this denies any traffic destined for out NAT egress address."
  direction = "INGRESS"
  destination_ranges = ["${google_compute_address.nat_egress_address.address}/32"]

  deny {
    protocol = "all"
  }
}
*/
```

**Comment by enocom** [comment] 2022-03-01 16:03
Did you see my second question?

> Can you reproduce this failure on a bare VM in the same VPC?

**Comment by enocom** [comment] 2022-05-06 03:39
Closing as stale. Feel free to re-open with any new information.

**Closed by enocom** 2022-05-06 03:39 UTC
Labels: type: question, needs more info
