### ISSUE TITLE
JWT Token error only on first time running Cloud SQL Proxy

### ISSUE THREAD

**Issue by patcombe** [GoogleCloudPlatform/cloudsql-proxy#589] opened 2021-01-13 21:11 UTC
## Bug Description

- Using Cloud SQL Proxy on RPi using a compiled version from GO. 
- Currently using bash script to open Cloud SQL Proxy upon device start. 
- I have noticed that the Cloud SQL Proxy does not connect on it's first attempt after the device has been off for a couple of hours. However, any subsequent device booting it will work. 
- I am not sure why it fails to connect just the first time after a long downtime period
- Error received: {"error": "invalid_grant", "error_description": "Invalid JWTL Token must be a short-lived token....
- Happy to provide any more info!

## Example code (or command)

```
./cloud_sql_proxy -instances=*****:us-east4:algorithm-library=tcp:1234 -credential_file=../../credentials/s****.json -term_timeout=30s  & 

```

## Stacktrace
```
Error received: {"error": "invalid_grant", "error_description": "Invalid JWTL Token must be a short-lived token....

```

## How to reproduce

  1. I am not entirely sure as it is a very specific case. 

## Environment

1. OS type and version: RPi Raspbian 
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): 1.18

**Comment by shubha-rajan** [comment] 2021-01-13 21:55
This looks like a duplicate of #588, so I'm going to close this and respond there.

**Closed by shubha-rajan** 2021-01-13 21:55 UTC
Labels: type: bug
