### ISSUE TITLE
Unable to pull gcr.io/cloudsql-docker/gce-proxy:latest image

### ISSUE THREAD

**Issue by jonathanbl** [GoogleCloudPlatform/cloudsql-proxy#619] opened 2021-02-17 20:35 UTC
Hi, 

Let me know if I need to provide more details but it seems like something has changed with the Docker image, we are not able to pull the gce-proxy image anymore (started around 3pm EST)

Executing `docker pull gcr.io/cloudsql-docker/gce-proxy:latest` with result into

```
Error response from daemon: Get https://gcr.io/v2/cloudsql-docker/gce-proxy/manifests/latest: denied: Project cloudsql-docker has been deleted.
```

Anything we are missing that could explain this?

Thank you!

**Comment by hollinwilkins** [comment] 2021-02-17 20:36
Seeing this issue as well

**Comment by kurtisvg** [comment] 2021-02-17 20:51
There was an issue with the project the images are hosted in. It should be restored now and access should be back (but we are working to confirm).

**Comment by jonathanbl** [comment] 2021-02-17 20:53
Thank you @kurtisvg - still seeing the error on our side but I guess there might be a delay like you mentioned

**Comment by natarajaya** [comment] 2021-02-17 20:56
Bumping into similar issue, probably related:
```
# docker pull gcr.io/cloudsql-docker/gce-proxy:1.19.1
Error response from daemon: pull access denied for gcr.io/cloudsql-docker/gce-proxy, repository does not exist or may require 'docker login': denied: Permission denied for "1.19.1" from request "/v2/cloudsql-docker/gce-proxy/manifests/1.19.1".
```

**Comment by kurtisvg** [comment] 2021-02-17 20:56
I think everything is spinning back up, I was seeing similar errors but they are coming back now.

**Comment by Carrotman42** [comment] 2021-02-17 20:58
I also saw the "pull access denied", and then a minute or two later I retried and it seems to be working.

Thank you to everyone who reported and reproduced this issue so quickly!

**Comment by dmahugh** [comment] 2021-02-18 17:17
Going to close this issue, and FYI we're doing a post-mortem internally to make sure this can't happen again. Apologies for the inconvenience.

**Closed by dmahugh** 2021-02-18 17:17 UTC
Labels: priority: p0, type: bug
